var dataeng = {
    beginnings: 
    [
        "Once upon a time there was ...",
        "One fine summer's day ...",
        "Long years ago, there lived ... who ...",
        "Once upon a time, and a very good time it was, though it wasn't in my time, nor in your time, nor anyone else's time ...",
        "It chanced that once upon a time long years ago, in the days when strange things used to happen in the world ...",
        "A girl once went",
        "There once lived a ... and a ... as many a one has been.",
        "A lad named ... was once so unhappy ...",
        "Near a pixy field in the neighbourhood of Dartmoor, there lived, on a time ...",
        "This, O my Best Beloved, is a story—a new and a wonderful story-a story quite different from the other stories ...",
        "Long before Arthur and the Knights of the Round Table ...",
        "There was once a man who ...",
        "In the days of the great King Arthur there lived ...",
        "Once upon a time when pigs spoke",
        "rhyme ...",
        "The date of foundation ...",
        "When was it mentioned",
        "Whan was it first discussed"
    ],
    places:
    [
        "Kingdom",
        "Village (countryside)",
        "Mountains",
        "Palace",
        "Forest",
        "Valley",
        "Meadow",
        "Lake",
        "Cave",
        "Sea",
        "River",
        "Moorland",
        "House",
        "Cemetery",
        "Border",
        "Farm"
    ],
    heroes:
    [
        "King",
        "Queden",
        "Princess",
        "Prince",
        "Knight",
        "Son",
        "Daughter",
        "Stepmother",
        "Pet",
        "Wife",
        "Husband",
        "Monk",
        "Animal (s)",
        "Mischief",
        "Wife",
        "Fairy",
        "Grandmother",
        "Grandad",
        "Children",
        "Widow",
        "Bachelor",
        "Widower",
        "Birds",
        "Servant",
        "Magician",
        "Rich man",
        "Peasant"
    ],
    phrases:
    [
        "First, ... Second, ..., Third, ... Finally",
        "On the one hand, ... On the other hand ... Some people believe Others ...",
        "Which, That, Who ...",
        "Since, as well as, though, unless ...",
        "Moreover, therefore, as a result, otherwise, besides",
        "For example ..., For instance ... such as ...",
        "If you ..., you will ...",
        "If I ..., I would ...",
        "In fact ...",
        "Generally speaking ...",
        "Frankly speaking ...",
        "To be honest with you I should say ...",
        "Well ...",
        "You see ...",
        "You know, ...",
        "I've never thought about it.",
        "That's a good question!",
        "All right,",
        "Sadly, ...",
        "Unfortunataly, ...",
        "Luckily, ..."

    ],
    magic:
    [
        "Grindylow",
        "Kumara",
        "Dracks",
        "Asrai",
        "Selki",
        "Leprekons",
        "Oaklets",
        "Brownie",
        "Green women",
        "Hillmen",
        "Giants",
        "Trolls",
        "Gleistig",
        "Gremlins",
        "Danny",
        "Baggeyn",
        "Grant",
        "Hobbits",
        "Topotun",
        "Werewold",
        "Akheron",
        "Bargest",
        "Kalyakh-vare",
        "Dobie",
        "Hobgoblin",
        "Bug",
        "Killmulis",
        "Klabauterman",
        "Boggart",
        "Fak-kahn",
        "Goblins",
        "Red Caps",
        "Hobii",
        "Orcs",
        "Gooseberry`s wife"
    ],
    magicobjects:
    [
        'Magic ointment',
        'Magic pipe',
        'A magical wand',
        'A birdie',
        'The hedge',
        'The wel',
        'The apple',
        'The pear',
        'The plum',
        'Magic ring',
        'Fairies’ cup'
    ],
    household:
    [
        "Spinning wheel",
        "Chest",
        "Box",
        "Dress",
        "Smart clothes",
        "Table",
        "Chair",
        "Bed",
        "Ring",
        "Crown",
        "Food",
        "Drinks",
        "Carpet",
        "Book",
        "Tree",
        "Broom",
        "Axe",
        "Hat",
        "Clock",
        "Bludgeon",
        "Kerchief",
        "Shoes",
        "Fireplace",
        "Purse",
        "Bag"
    ],
    ending:
    [
        '…and they all lived happy and died happy, and never drank out of a dry cappy.',
        '…and they lived happy ever afterwards.',
        "… till the day of her death.",
        "…and they all lived happy as could be ever afterwards.",
        "And they were married, and he and she are living happy to this day for aught I know.",
        "That's all",
        "…and was never seen again.",
        "And they lived happy all their days.",
        "Now I can say...",
        "I wish in conclusion to express the opinion"   
    ]

  };


  var databel = {
    beginnings: 
    [
        "Было ў аднаго чалавека ...",
        "Жылі ...",
        "Быў раз ...",
        "Жылі былі ў адной вёсцы ...",
        "У адзін ясны сонечны дзень ...",
        "У аднаго караля быў...",
        "Быў такі час на зямлі, калі ...",
        "Было гэта даўным-даўно, калі ...",
        "Жыў некалі ..."
    ],
    places:
    [
        "Вёска",
        "Лес",
        "Рака",
        "Возера",
        "Хата",
        "Балота",
        "Дрыгва",
        "Горад",
        "Поле",
        "Луг",
        "Бор",
        "Двор",
        "Млын",
        "Фабрыка",
        "Хутар",
        "Царства",
        "Ферма"
    ],
    heroes:
    [
        "Цар",
        "Царэўна",
        "Царэвіч",
        "Царыца",
        "Сын",
        "Дачка",
        "Маці",
        "Тата",
        "Муж",
        "Жанка",
        "Унук",
        "Унучка",
        "Старац",
        "Поп",
        "Жывёлы",
        "Птушкі",
        "Бедняк",
        "Багач",
        "Ведзьма",
        "Слуга",
        "Удава",
        "Сялянін",
        "Сялянка"
    ],
    phrases:
    [
        "First, ... Second, ..., Third, ... Finally",
        "On the one hand, ... On the other hand ... Some people believe Others ...",
        "Which, That, Who ...",
        "Since, as well as, though, unless ...",
        "Moreover, therefore, as a result, otherwise, besides",
        "For example ..., For instance ... such as ...",
        "If you ..., you will ...",
        "If I ..., I would ...",
        "In fact ...",
        "Generally speaking ...",
        "Frankly speaking ...",
        "To be honest with you I should say ...",
        "Well ...",
        "You see ...",
        "You know, ...",
        "I've never thought about it.",
        "That's a good question!",
        "All right,",
        "Sadly, ...",
        "Unfortunataly, ...",
        "Luckily, ..."

    ],
    magic:
    [
        "Grindylow",
        "Kumara",
        "Dracks",
        "Asrai",
        "Selki",
        "Leprekons",
        "Oaklets",
        "Brownie",
        "Green women",
        "Hillmen",
        "Giants",
        "Trolls",
        "Gleistig",
        "Gremlins",
        "Danny",
        "Baggeyn",
        "Grant",
        "Hobbits",
        "Topotun",
        "Werewold",
        "Akheron",
        "Bargest",
        "Kalyakh-vare",
        "Dobie",
        "Hobgoblin",
        "Bug",
        "Killmulis",
        "Klabauterman",
        "Boggart",
        "Fak-kahn",
        "Goblins",
        "Red Caps",
        "Hobii",
        "Orcs",
        "Gooseberry`s wife"
    ],
    magicobjects:
    [
        'gg',
        'gg',
        'gg'
    ],
    household:
    [
        "Печ",
        "Ложак",
        "Стол",
        "Лаўка",
        "Кальцо",
        "Мятла",
        "Вежа",
        "Напой",
        "Кніга",
        "Дрэва",
        "Посуд",
        "Дыван",
        "Сякера",
        "Хустка",
        "Адзежа",
        "Абутак",
        "Дубіна",
        "Ачаг",
        "Кошак",
        "Кашалёк",
        "Торба"
    ],
    ending:
    [
        '…and they all lived happy and died happy, and never drank out of a dry cappy.',
        '…and they lived happy ever afterwards.',
        "… till the day of her death.",
        "…and they all lived happy as could be ever afterwards.",
        "And they were married, and he and she are living happy to this day for aught I know.",
        "That's all",
        "…and was never seen again.",
        "And they lived happy all their days.",
        "Now I can say...",
        "I wish in conclusion to express the opinion"   
    ]

  };


var data = dataeng;