var dataeng = {
    beginnings: 
    [
        "Once upon a time there was ...",
        "One fine summer's day ...",
        "Long years ago, there lived ... who ...",
        "Once upon a time, and a very good time it was, though it wasn't in my time, nor in your time, nor anyone else's time ...",
        "It chanced that once upon a time long years ago, in the days when strange things used to happen in the world ...",
        "A girl once went",
        "There once lived a ... and a ... as many a one has been.",
        "A lad named ... was once so unhappy ...",
        "Near a pixy field in the neighbourhood of Dartmoor, there lived, on a time ...",
        "This, O my Best Beloved, is a story—a new and a wonderful story-a story quite different from the other stories ...",
        "Long before Arthur and the Knights of the Round Table ...",
        "There was once a man who ...",
        "In the days of the great King Arthur there lived ...",
        "Once upon a time when pigs spoke rhyme ...",
        "The date of foundation ...",
        "When was it mentioned",
        "When was it first discussed"
    ],
    places:
    [
        "Kingdom",
        "Village (countryside)",
        "Mountains",
        "Palace",
        "Forest",
        "Valley",
        "Meadow",
        "Lake",
        "Cave",
        "Sea",
        "River",
        "Moorland",
        "House",
        "Cemetery",
        "Border",
        "Farm"
    ],
    heroes:
    [
        "King",
        "Queden",
        "Princess",
        "Prince",
        "Knight",
        "Son",
        "Daughter",
        "Stepmother",
        "Pet",
        "Wife",
        "Husband",
        "Monk",
        "Animal (s)",
        "Mischief",
        "Wife",
        "Fairy",
        "Grandmother",
        "Grandad",
        "Children",
        "Widow",
        "Bachelor",
        "Widower",
        "Birds",
        "Servant",
        "Magician",
        "Rich man",
        "Peasant"
    ],
    phrases:
    [
        "First, ... Second, ..., Third, ... Finally",
        "On the one hand, ... On the other hand ... Some people believe Others ...",
        "Which, That, Who ...",
        "Since, as well as, though, unless ...",
        "Moreover, therefore, as a result, otherwise, besides",
        "For example ..., For instance ... such as ...",
        "If you ..., you will ...",
        "If I ..., I would ...",
        "In fact ...",
        "Generally speaking ...",
        "Frankly speaking ...",
        "To be honest with you I should say ...",
        "Well ...",
        "You see ...",
        "You know, ...",
        "I've never thought about it.",
        "That's a good question!",
        "All right,",
        "Sadly, ...",
        "Unfortunately, ...",
        "Luckily, ..."

    ],
    magic:
    [
        "Grindylow",
        "Kumara",
        "Dracks",
        "Asrai",
        "Selki",
        "Leprekons",
        "Oaklets",
        "Brownie",
        "Green women",
        "Hillmen",
        "Giants",
        "Trolls",
        "Gleistig",
        "Gremlins",
        "Danny",
        "Baggeyn",
        "Grant",
        "Hobbits",
        "Topotun",
        "Werewold",
        "Akheron",
        "Bargest",
        "Kalyakh-vare",
        "Dobie",
        "Hobgoblin",
        "Bug",
        "Killmulis",
        "Klabauterman",
        "Boggart",
        "Fak-kahn",
        "Goblins",
        "Red Caps",
        "Hobii",
        "Orcs",
        "Gooseberry`s wife"
    ],
    magicobjects:
    [
        'Magic ointment',
        'Magic pipe',
        'A magical wand',
        'A birdie',
        'The hedge',
        'The well',
        'The apple',
        'The pear',
        'The plum',
        'Magic ring',
        'Fairy cup'
    ],
    household:
    [
        "Spinning wheel",
        "Chest",
        "Box",
        "Dress",
        "Smart clothes",
        "Table",
        "Chair",
        "Bed",
        "Ring",
        "Crown",
        "Food",
        "Drinks",
        "Carpet",
        "Book",
        "Tree",
        "Broom",
        "Axe",
        "Hat",
        "Clock",
        "Bludgeon",
        "Kerchief",
        "Shoes",
        "Fireplace",
        "Purse",
        "Bag"
    ],
    actions:
    [
        'Went (to / abroad / for away',
        "Played (smth / with smb)",
        "Put (a spell on smb)",
        "Gave (smth to smb)",
        "Rode (horseback / horse to death / a race)",
        "Took (a risk)",
        "Saw (into the future / smb / smth",
        "Cried (eyes out / for the moon / out",
        "Made (of / a sound / trouble / a decision",
        "Told / said / spoke",
        "Knew (What's what / right from wrong",
        "Ran (out of smth / away / a risk)",
        "Found (dead / out that...)",
        "Travelled (light / far from / alone)",
        "Saved (life / oneself / for a rainy day",
        "Disappeared (from smb's view / forever)"
    ],
    ending:
    [
        '…and they all lived happy and died happy, and never drank out of a dry cappy.',
        '…and they lived happy ever afterwards.',
        "… till the day of her death.",
        "…and they all lived happy as could be ever afterwards.",
        "And they were married, and he and she are living happy to this day for aught I know.",
        "That's all",
        "…and was never seen again.",
        "And they lived happy all their days.",
        "Now I can say...",
        "I wish in conclusion to express the opinion"   
    ]

  };


  var databel = {
    beginnings: 
    [
        "Было ў аднаго чалавека ...",
        "Жылі ...",
        "Быў раз ...",
        "Жылі былі ў адной вёсцы ...",
        "У адзін ясны сонечны дзень ...",
        "У аднаго караля быў...",
        "Быў такі час на зямлі, калі ...",
        "Было гэта даўным-даўно, калі ...",
        "Жыў некалі ..."
    ],
    places:
    [
        "Вёска",
        "Лес",
        "Рака",
        "Возера",
        "Хата",
        "Балота",
        "Дрыгва",
        "Горад",
        "Поле",
        "Луг",
        "Бор",
        "Двор",
        "Млын",
        "Фабрыка",
        "Хутар",
        "Царства",
        "Ферма"
    ],
    heroes:
    [
        "Цар",
        "Царэўна",
        "Царэвіч",
        "Царыца",
        "Сын",
        "Дачка",
        "Маці",
        "Тата",
        "Муж",
        "Жонка",
        "Унук",
        "Унучка",
        "Старац",
        "Поп",
        "Жывёлы",
        "Птушкі",
        "Бедняк",
        "Багач",
        "Ведзьма",
        "Слуга",
        "Удава",
        "Селянін",
        "Сялянка"
    ],
    phrases:
    [
        "Спачатку... Потым... А пасля... Напрыканцы",
        "З аднаго боку... З другога боку...",
        "Негледзячы на...",
        "Так цi iнакш...",
        "Хочаш ня хочаш...",
        "Акрамя таго...",
        "Вiдавочна...",
        "Знянацку...",
        "Праз нейкi час",
        "Нi..., нi...",
        "З таго часу...",
        "Аля...",
        "Шчыра кажуць",
        "На самай справе...",
        "Напрыклад...",
        "iшоў-iшоў...",
        "Калi... дык...",
        "Ажно...",
        "На шчасце...",
        "Да няшчасця..."
    ],
    magic:
    [
        "Вадзянiк",
        "Балотнiк",
        "Жэўжык",
        "Лазовiк",
        "Азёрнiцы",
        "Аржавенiк",
        "Цар-рыба",
        "Хаджун",
        "Вужыны цар",
        "Вужакi",
        "Ягiня",
        "Зазувкi",
        "Гарцук",
        "Паветрiкi",
        "Дамавiк",
        "Еўнiк",
        "Хлеўнiк",
        "Пячурнiк",
        "Хатнiк",
        "Жыцень",
        "Асiлак",
        "Дзедка",
        "Дзяды",
        "Хапун",
        "Жалезная бабка",
        "Трасца",
        "Расамаха",
        "Валасень",
        "Сярбай",
        "Злыдзень",
        "Кумяльган",
        "Белая смерць",
        "Гагатун"
    ],
    magicobjects:
    [
        'Чароўныя лекi',
        'Чароўная палачка',
        'Яблык',
        'Слiва',
        'Чароўны кубак',
        'Чароўная дудка',
        'Птушка',
        'Калодзеж',
        'Чароўнае кальцо',
        'Груша',
        'Верасцяно',
        'Торба'
    ],
    household:
    [
        "Печ",
        "Ложак",
        "Стол",
        "Лаўка",
        "Кальцо",
        "Мятла",
        "Вежа",
        "Напой",
        "Кніга",
        "Дрэва",
        "Посуд",
        "Дыван",
        "Сякера",
        "Хустка",
        "Адзежа",
        "Абутак",
        "Дубіна",
        "Ачаг",
        "Кошак",
        "Кашалёк",
        "Торба"
    ],
    actions:
    [
        'Выправiў',
        'Прыставiў',
        'Задрамаў',
        'Пайшоў',
        'Сеў',
        'Усьмiхнуўся',
        'Прытаiўся',
        'Жыў',
        'Спадабаўся',
        'Паслухаў',
        'Зажмурыўся',
        'Гадаваў',
        'Пытаецца',
        'Пачаў скардзiцца',
        'Плача',
        'Кажа',
        'Здзiвiўся',
        'Прыскакаў'
    ],
    ending:
    [
        'А злую мачаху і яе дачку больш да сабе і на парог не пускалі.',
        'Байку вам сказаў, усе роўна як звязаў, а тыя ўсё жывуць, мёд, віно п’юць, мне не даюць.',
        "Усяго там было: хто хацеў, той піў і еў. І я там быў, еў і піў, па барадзе цяк-ло, а ў роце не было.",
        "Так з таго часу і жыве з куртатым хвастом.",
        "Пачуўшы гэта, пан усхапіўся на ногі і так драпануў назад у свой маёнтак, што толькі яго і бачылі.",
        "З таго часу больш і не сябруюць саба-ка з ваўком.",
        "Пачуўшы такія навіны, пан зваліўся з крэсла, а Сцёпка закурыў люлечку ды падаўся сабе да хаты.",
        "І сталі яны жыць-пажываць і дабра нажываць.",
        "Так і стаў дурань панаваць у Змеевым двары. Праўда, разумнейшым ён не стаў. Але нашто багатаму розум? У ка-го грошай стае, дык і розум дае!",
        "З таго часу ён і баіцца сустракацца з чалавекам."   
    ]

  };


var data = dataeng;